# Generated by Django 4.1.1 on 2022-09-18 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_chapters', to='course.course'),
        ),
        migrations.AlterField(
            model_name='task',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapter_tasks', to='course.chapter'),
        ),
    ]
