# Generated by Django 4.1.1 on 2022-09-19 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_chapter_course_alter_task_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_comment_course', to='course.coursecomment'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_comment_task', to='course.taskcomment'),
        ),
    ]
