# Generated by Django 4.1.1 on 2022-09-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_coursecomment_parent_alter_taskcomment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecomment',
            options={'verbose_name': 'Комментарий Курса', 'verbose_name_plural': 'Комментарии Курса'},
        ),
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'verbose_name': 'Комментарий Темы', 'verbose_name_plural': 'Комментарии Темы'},
        ),
    ]
