# Generated by Django 4.1.1 on 2022-09-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_coursecomment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecomment',
            options={'ordering': ['-date'], 'verbose_name': 'Комментарий Курса', 'verbose_name_plural': 'Комментарии Курса'},
        ),
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['-date'], 'verbose_name': 'Комментарий Темы', 'verbose_name_plural': 'Комментарии Темы'},
        ),
    ]
