# Generated by Django 4.1.1 on 2022-09-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_coursecomment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': 'Глава', 'verbose_name_plural': 'Главы'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
    ]
