# Generated by Django 4.1.1 on 2023-10-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_chapter_course_alter_chapter_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview',
            field=models.CharField(default=1, max_length=123, verbose_name='Контент'),
            preserve_default=False,
        ),
    ]
