# Generated by Django 4.1.1 on 2022-09-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='preview',
            field=models.CharField(blank=True, default='Подробнее...', max_length=100, null=True),
        ),
    ]
