# Generated by Django 4.1.1 on 2022-09-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_article_description_alter_mention_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_prior',
            field=models.BooleanField(default=False, verbose_name='Важная новость'),
        ),
    ]
