# Generated by Django 4.1.1 on 2022-09-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_eventcategory_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='preview',
            field=models.CharField(blank=True, default='Подробнее', max_length=155, null=True),
        ),
    ]
