# Generated by Django 4.1.1 on 2022-09-30 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_events_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.eventcategory'),
        ),
    ]
