# Generated by Django 4.1.1 on 2022-09-30 05:55

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_eventcategory_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=144, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('navbar', models.BooleanField(default=False, verbose_name='На главную страничку')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'Отдельная страница',
                'verbose_name_plural': 'Отдельные страницы',
            },
        ),
    ]
