# Generated by Django 4.1.1 on 2022-10-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_article_date_alter_article_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='rer',
            field=models.ManyToManyField(blank=True, to='home.partner', verbose_name='Партнеры'),
        ),
    ]
