# Generated by Django 4.1.1 on 2022-10-14 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_events_rer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCatery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
            ],
            options={
                'verbose_name': 'Страница на сайте',
                'verbose_name_plural': 'Страницы на сайте',
            },
        ),
        migrations.RemoveField(
            model_name='otherpage',
            name='navbar',
        ),
        migrations.AlterField(
            model_name='events',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='news',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=122, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_vrach',
            field=models.BooleanField(default=False, verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=122, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='otherpage',
            name='on_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pagecategory', to='home.pagecatery', verbose_name='Категория страницы'),
            preserve_default=False,
        ),
    ]
