# Generated by Django 4.1.1 on 2022-10-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_pagecatery_remove_otherpage_navbar_alter_events_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatars/', verbose_name='Аватар'),
        ),
    ]
