# Generated by Django 4.1.1 on 2022-10-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsimage',
            name='news',
        ),
    ]
